// Copyright 2023 The Forgotten Server Authors. All rights reserved.
// Use of this source code is governed by the GPL-2.0 License that can be found in the LICENSE file.

#ifndef FS_CONFIGMANAGER_H
#define FS_CONFIGMANAGER_H

namespace ConfigManager {

enum Boolean
{
	ALLOW_CHANGEOUTFIT,
	ONE_PLAYER_ON_ACCOUNT,
	AIMBOT_HOTKEY_ENABLED,
	SPAWN_START_EFFECT_ENABLED,
	REMOVE_RUNE_CHARGES,
	REMOVE_WEAPON_AMMO,
	REMOVE_WEAPON_CHARGES,
	REMOVE_POTION_CHARGES,
	FAST_POTIONS_ENABLED,
	EXPERIENCE_FROM_PLAYERS,
	FREE_PREMIUM,
	REPLACE_KICK_ON_LOGIN,
	ALLOW_CLONES,
	ALLOW_WALKTHROUGH,
	BIND_ONLY_GLOBAL_ADDRESS,
	OPTIMIZE_DATABASE,
	MARKET_PREMIUM,
	EMOTE_SPELLS,
	STAMINA_SYSTEM,
	WARN_UNSAFE_SCRIPTS,
	CONVERT_UNSAFE_SCRIPTS,
	CLASSIC_EQUIPMENT_SLOTS,
	LIVE_CAST_ENABLED,
	CAST_EXP_BONUS,
	CLASSIC_ATTACK_SPEED,
	SCRIPTS_CONSOLE_LOGS,
	SERVER_SAVE_NOTIFY_MESSAGE,
	SERVER_SAVE_CLEAN_MAP,
	SERVER_SAVE_CLOSE,
	SERVER_SAVE_SHUTDOWN,
	ONLINE_OFFLINE_CHARLIST,
	YELL_ALLOW_PREMIUM,
	PREMIUM_TO_SEND_PRIVATE,
	FORCE_MONSTERTYPE_LOAD,
	DEFAULT_WORLD_LIGHT,
	HOUSE_OWNED_BY_ACCOUNT,
	CLEAN_PROTECTION_ZONES,
	HOUSE_DOOR_SHOW_PRICE,
	ONLY_INVITED_CAN_MOVE_HOUSE_ITEMS,
	REMOVE_ON_DESPAWN,
	MONSTER_OVERSPAWN,
	MANASHIELD_BREAKABLE,
	BED_OFFLINE_TRAINING,
	ALLOW_AUTO_ATTACK_WITHOUT_EXHAUSTION,
	ALLOW_CASTING_WHILE_WALKING,
	ACCOUNT_MANAGER,
	NAMELOCK_MANAGER,
	START_CHOOSEVOC,
	GENERATE_ACCOUNT_NUMBER,
	CHECK_DUPLICATE_STORAGE_KEYS,
	PACKET_COMPRESSION,	
	DLL_CHECK_KICK,
	RESET_SYSTEM_ENABLED, // reset system
	NPCS_USING_BANK_MONEY,	
	STAMINA_TRAINER,
	STAMINA_PZ,
	AUTOLOOT_ENABLED,
	ADMIN_LOCALHOST_ONLY,
	ADMIN_REQUIRE_LOGIN,
	ADMIN_LOGS,

	LAST_BOOLEAN /* this must be the last one */
};

enum String
{
	MAP_NAME,
	HOUSE_RENT_PERIOD,
	SERVER_NAME,
	OWNER_NAME,
	OWNER_EMAIL,
	URL,
	LOCATION,
	IP,
	MOTD,
	WORLD_TYPE,
	MYSQL_HOST,
	MYSQL_USER,
	MYSQL_PASS,
	MYSQL_DB,
	MYSQL_SOCK,
	DEFAULT_PRIORITY,
	MAP_AUTHOR,
	CONFIG_FILE,
	LOG_LEVEL,
	AUTOLOOT_BLOCKIDS,
	AUTOLOOT_MONEYIDS,
	ADMIN_PASSWORD,
	ADMIN_ENCRYPTION,
	ADMIN_ENCRYPTION_DATA,

	LAST_STRING /* this must be the last one */
};

enum StringList
{
	FAST_POTION_IDS,
	BLOCKED_TELEPORT_IDS,

	LAST_STRING_LIST /* this must be the last one */
};

enum Integer
{
	SQL_PORT,
	MAX_PLAYERS,
	PZ_LOCKED,
	DEFAULT_DESPAWNRANGE,
	DEFAULT_DESPAWNRADIUS,
	DEFAULT_WALKTOSPAWNRADIUS,
	RATE_EXPERIENCE,
	RATE_SKILL,
	RATE_LOOT,
	RATE_MAGIC,
	RATE_SPAWN,
	RATE_START_EFFECT,
	RATE_BETWEEN_EFFECT,
	HOUSE_LEVEL,
	HOUSE_PRICE,
	KILLS_TO_RED,
	KILLS_TO_BLACK,
	MAX_MESSAGEBUFFER,
	ACTIONS_DELAY_INTERVAL,
	EX_ACTIONS_DELAY_INTERVAL,
	KICK_AFTER_MINUTES,
	PROTECTION_LEVEL,
	DEATH_LOSE_PERCENT,
	STATUSQUERY_TIMEOUT,
	STATUS_COUNT_MAX_PLAYERS_PER_IP,
	FRAG_TIME,
	WHITE_SKULL_TIME,
	GAME_PORT,
	LOGIN_PORT,
	STATUS_PORT,
	ADMIN_PORT,
	ADMIN_CONNECTIONS_LIMIT,
	STAIRHOP_DELAY,
	MARKET_OFFER_DURATION,
	EXP_SHARE_RANGE,
	EXP_SHARE_FLOORS,
	EXP_FROM_PLAYERS_LEVEL_RANGE,
	MAX_PACKETS_PER_SECOND,
	LIVE_CAST_PORT,
	LIVE_CAST_MAX,
	CAST_EXP_BONUS_PERCENT,
	SERVER_SAVE_NOTIFY_DURATION,
	YELL_MINIMUM_LEVEL,
	MINIMUM_LEVEL_TO_SEND_PRIVATE,
	VIP_FREE_LIMIT,
	VIP_PREMIUM_LIMIT,
	DEPOT_FREE_LIMIT,
	DEPOT_PREMIUM_LIMIT,
	STAMINA_REGEN_MINUTE,
	STAMINA_REGEN_PREMIUM,
	STAMINA_PZ_GAIN,
	STAMINA_ORANGE_DELAY,
	STAMINA_GREEN_DELAY,
	STAMINA_TRAINER_DELAY,
	STAMINA_TRAINER_GAIN,
	HEALTH_GAIN_COLOUR,
	MANA_GAIN_COLOUR,
	MANA_LOSS_COLOUR,
	MAX_PROTOCOL_OUTFITS,
	MOVE_CREATURE_INTERVAL,
	RANGE_MOVE_CREATURE_INTERVAL,
	RANGE_USE_WITH_CREATURE_INTERVAL,
	RANGE_MOVE_ITEM_INTERVAL,
	RANGE_USE_ITEM_INTERVAL,
	RANGE_USE_ITEM_EX_INTERVAL,
	RANGE_ROTATE_ITEM_INTERVAL,
	MAX_PLAYER_SPEED,
	MAX_GOD_SPEED,
	NEW_PLAYER_SPAWN_POS_X,
	NEW_PLAYER_SPAWN_POS_Y,
	NEW_PLAYER_SPAWN_POS_Z,
	NEW_PLAYER_TOWN_ID,
	NEW_PLAYER_LEVEL,
	NEW_PLAYER_MAGIC_LEVEL,
	NEW_PLAYER_HEALTH,
	NEW_PLAYER_MANA,
	NEW_PLAYER_CAP,
	MAX_ALLOWED_ON_A_DUMMY,
	RATE_EXERCISE_TRAINING_SPEED,
	DLL_CHECK_KICK_TIME,
	RESET_LEVEL,
	RESET_STATBONUS,
	RESET_DMGBONUS,
	RESET_REDUCTION_PERCENTAGE,
	OFFLINE_TRAINING_THRESHOLD,

	STATS_DUMP_INTERVAL,
	STATS_SLOW_LOG_TIME,
	STATS_VERY_SLOW_LOG_TIME,

	AUTOLOOT_MAXITEMS_FREE,
	AUTOLOOT_MAXITEMS_PREMIUM,

	LAST_INTEGER /* this must be the last one */
};

enum float_config_t
{
	REWARD_BASE_RATE,
	REWARD_RATE_DAMAGE_DONE,
	REWARD_RATE_DAMAGE_TAKEN,
	REWARD_RATE_HEALING_DONE,
	OFFLINE_TRAINING_EFFICIENCY,
	OFFLINE_TRAINING_MAGE_ML,
	OFFLINE_TRAINING_PALADIN_DIST,
	OFFLINE_TRAINING_PALADIN_ML,
	OFFLINE_TRAINING_PALADIN_SHIELD,
	OFFLINE_TRAINING_KNIGHT_MELEE,
	OFFLINE_TRAINING_KNIGHT_SHIELD,
	LAST_FLOAT_CONFIG /* this must be the last one */
};

bool load();

bool getBoolean(Boolean what);
std::string_view getString(String what);
int64_t getInteger(Integer what);
float getFloat(float_config_t what);
float getExperienceStage(uint32_t level);
const std::vector<uint16_t>& getFastPotionIds();
const std::vector<uint16_t>& getBlockedTeleportIds();

bool setBoolean(Boolean what, bool value);
bool setString(String what, std::string_view value);
bool setInteger(Integer what, int64_t value);
bool setFloat(float_config_t what, float value);
} // namespace ConfigManager

#endif // FS_CONFIGMANAGER_H
